services:
  tor:
    build: .
    container_name: tor-relay
    volumes:
      - ./torrc:/etc/tor/torrc
      - ./tor-data:/var/lib/tor
    ports:
      - "9001:9001"
    restart: unless-stopped
    network_mode: host
